config/routes.rb
ImmonetCheater::Application.routes.draw do
  resources :immonet_links

  resources :immonet_mails

  devise_for :users

  root "immonet_mails#index"
end

app/models/immonet_mail.rb
class ImmonetMail < ActiveRecord::Base
  serialize :headers, Hash

  has_many :immonet_links, dependent: :destroy

  after_create :create_immonet_links

  def create_immonet_links
    links.each do |link|
      immonet_links.create link: link
    end
  end

  def links
    return body.gsub(/(http.*immonet.*(angebot|exposeanzeige|exposeansicht).*)(>|\s)/).map{ $1 }.uniq
    #if subject.strip.eql? 'contact!'
    #  body.each_line.map(&:strip).select{|l| l.start_with? 'http'}
    #else
    #end
  end

  def self.fetch
    Mail.defaults do
      retriever_method :imap, { :address             => "arrowsoft.de",
                                :user_name           => 'immonet@arrowsoft.de',
                                :password            => ''}
    end

    mails = Mail.find(keys: "NEW")


    mails.each do |mail|
      data = {}
      text_part = mail.parts.find{|p| p.content_type.include? 'text/plain'}
      data[:body] = text_part.decoded
      data[:raw] = mail.raw_source
      data[:subject] = mail.subject
      data[:headers] = {}

      data[:headers] = {}

      mail.header.fields.each do |field|
        data[:headers][field.name.to_s] = field.value
      end

      immonet_mail = create(data)
      immonet_mail.immonet_links.where(status: nil).each(&:contact)
    end
  end
end

app/controllers/immonet_mails_controller.rb
class ImmonetMailsController < ApplicationController
  before_action :set_immonet_mail, only: [:show, :edit, :update, :destroy]

  # GET /immonet_mails
  # GET /immonet_mails.json
  def index
    @immonet_mails = ImmonetMail.all
  end

  # GET /immonet_mails/1
  # GET /immonet_mails/1.json
  def show
  end

  # GET /immonet_mails/new
  def new
    @immonet_mail = ImmonetMail.new
  end

  # GET /immonet_mails/1/edit
  def edit
  end

  # POST /immonet_mails
  # POST /immonet_mails.json
  def create
    @immonet_mail = ImmonetMail.new(immonet_mail_params)

    respond_to do |format|
      if @immonet_mail.save
        format.html { redirect_to @immonet_mail, notice: 'Immonet mail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @immonet_mail }
      else
        format.html { render action: 'new' }
        format.json { render json: @immonet_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /immonet_mails/1
  # PATCH/PUT /immonet_mails/1.json
  def update
    respond_to do |format|
      if @immonet_mail.update(immonet_mail_params)
        format.html { redirect_to @immonet_mail, notice: 'Immonet mail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @immonet_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /immonet_mails/1
  # DELETE /immonet_mails/1.json
  def destroy
    @immonet_mail.destroy
    respond_to do |format|
      format.html { redirect_to immonet_mails_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_immonet_mail
      @immonet_mail = ImmonetMail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def immonet_mail_params
      if params[:immonet_mail_json]
        JSON.parse params[:immonet_mail_json]
      else
        params.require(:immonet_mail).permit(:body, :subject, :headers, :raw)
      end
    end
end

app/helpers/immonet_mails_helper.rb
module ImmonetMailsHelper
end

app/views/immonet_mails/_form.html.haml
= simple_form_for(@immonet_mail) do |f|
  = f.error_notification

  .form-inputs
    = f.input :body
    = f.input :subject
    = f.input :headers
    = f.input :raw

  .form-actions
    = f.button :submit

app/views/immonet_mails/edit.html.haml
%h1 Editing immonet_mail

= render 'form'

= link_to 'Show', @immonet_mail
\|
= link_to 'Back', immonet_mails_path

app/views/immonet_mails/index.html.haml
%h1 Listing immonet_mails

%table
  %tr
    %th Body
    %th Subject
    %th Headers
    %th Raw
    %th
    %th
    %th

  - @immonet_mails.each do |immonet_mail|
    %tr
      %td= immonet_mail.body
      %td= immonet_mail.subject
      %td= immonet_mail.headers
      %td= immonet_mail.raw
      %td= link_to 'Show', immonet_mail
      %td= link_to 'Edit', edit_immonet_mail_path(immonet_mail)
      %td= link_to 'Destroy', immonet_mail, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Immonet mail', new_immonet_mail_path

app/views/immonet_mails/new.html.haml
%h1 New immonet_mail

= render 'form'

= link_to 'Back', immonet_mails_path

app/views/immonet_mails/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @immonet_mail.body
%p
  %b Subject:
  = @immonet_mail.subject
%p
  %b Headers:
  = @immonet_mail.headers
%p
  %b Raw:
  = @immonet_mail.raw

= link_to 'Edit', edit_immonet_mail_path(@immonet_mail)
\|
= link_to 'Back', immonet_mails_path