config/routes.rb
ImmonetCheater::Application.routes.draw do
  resources :immonet_links

  resources :immonet_mails

  devise_for :users

  root "immonet_mails#index"
end

app/models/immonet_link.rb
class ImmonetLink < ActiveRecord::Base
  belongs_to :immonet_mail

  validates_uniqueness_of :immonet_id

  def link= link
    self.immonet_id ||= link[/public_id=(\d*)/,1] || link[/object_id=(\d*)/,1] || link[/angebot\/(\d*)/,1]
    super(link)
  end

  def contact
    self.increment! :retry_count
    begin
      driver = Selenium::WebDriver.for :phantomjs
      #driver = Selenium::WebDriver.for :firefox
      driver.manage.timeouts.implicit_wait = 10

      driver.navigate.to link
      return if not_found_error(driver)
      driver.save_screenshot Rails.root.join('public','screenshots',"#{self.id}-#{self.immonet_id}-#{self.retry_count}-main.png")

      tries ||= 2
      begin
        driver.find_element(css: 'a#expkb2').click
      rescue
        retry unless (tries -= 1).zero?
        driver.find_element(css: 'a#expkb2').click
      end
      elements = {}

      form_data.each do |field, value|
        el = driver.find_element(css: '#' + field)

        if el.tag_name.eql? 'select'
          el.click
          el.find_element(css: "option[value=#{value}]").click
        else
          el.clear
          el.send_keys value
        end
      end
      driver.find_element(css: '#bc_perambulation').click
      driver.save_screenshot Rails.root.join('public','screenshots',"#{self.id}-#{self.immonet_id}-#{self.retry_count}-form.png")
      driver.find_element(css: 'button#sendLongContactForm').click

      self.update status: 'contacted'
      driver.save_screenshot Rails.root.join('public','screenshots',"#{self.id}-#{self.immonet_id}-#{self.retry_count}-send.png")
    rescue Exception=>e
      return if not_found_error(driver)
      Rails.logger.error e.to_s
      self.update status: 'error', error_message: "#{e.to_s} \n\n #{self.error_message}"
    end
  end

  private

  def not_found_error driver
    if driver.current_url.include? 'objektNichtGefunden'
      self.update status: 'not found'
      return true
    end
    return false
  end

  def form_data
    {
      'bc_salutation' => 'Herr',
      'bc_prename' => 'Bastian',
      'bc_surname' => 'Kriesten',
      'bc_email' => "bastian@kriesten.net",
      'bc_phone' => "0160 / 90151218",
      'bc_annotations' => <<eos

Guten Tag,

ihr Angebot klingt sehr zu uns passend, daher würden wir gerne zeitnah einen Termin für eine Besichtigung vereinbaren. Wir können am Wochenende und wochentags ab 17:30 Uhr.

Wir sind ein Akademiker-Pärchen (beide 31 Jahre alt) mit unbefristeten Jobs in Hamburg. Wir haben keine Haustiere. Wir sind Nichtraucher und suchen eine Nichtraucherwohnung.

Ich arbeite als Software-Entwickler in der Internetbranche (http:/www.jimdo.de) und meine Partnerin ist in der Unternehmensberatung als Projektleiterin tätig (http://www.beone-hamburg.com/).
Eine kleine Selbstauskunft finden Sie unter http://kriesten.net/Selbstauskunft_Kriesten_Peters.pdf.

Wir freuen uns über eine zeitnahe Antwort.

Mit freundlichen Grüßen,

Bastian Kriesten (Diplom Informatiker)
Annika Peters (Dr.-Ing.)


Kontakt:
Bastian Kriesten
Mail: bastian@kriesten.net

Professor-Brix-Weg 7
22767 Hamburg

eos

}

  end
end

app/controllers/immonet_links_controller.rb
class ImmonetLinksController < ApplicationController
  before_action :set_immonet_link, only: [:show, :edit, :update, :destroy]

  # GET /immonet_links
  # GET /immonet_links.json
  def index
    @immonet_links = ImmonetLink.all
  end

  # GET /immonet_links/1
  # GET /immonet_links/1.json
  def show
  end

  # GET /immonet_links/new
  def new
    @immonet_link = ImmonetLink.new
  end

  # GET /immonet_links/1/edit
  def edit
  end

  # POST /immonet_links
  # POST /immonet_links.json
  def create
    @immonet_link = ImmonetLink.new(immonet_link_params)

    respond_to do |format|
      if @immonet_link.save
        format.html { redirect_to @immonet_link, notice: 'Immonet link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @immonet_link }
      else
        format.html { render action: 'new' }
        format.json { render json: @immonet_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /immonet_links/1
  # PATCH/PUT /immonet_links/1.json
  def update
    respond_to do |format|
      if @immonet_link.update(immonet_link_params)
        format.html { redirect_to @immonet_link, notice: 'Immonet link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @immonet_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /immonet_links/1
  # DELETE /immonet_links/1.json
  def destroy
    @immonet_link.destroy
    respond_to do |format|
      format.html { redirect_to immonet_links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_immonet_link
      @immonet_link = ImmonetLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def immonet_link_params
      params.require(:immonet_link).permit(:immonet_mail_id, :object_id, :link, :status)
    end
end

app/helpers/immonet_links_helper.rb
module ImmonetLinksHelper
end

app/views/immonet_links/_form.html.haml
= simple_form_for(@immonet_link) do |f|
  = f.error_notification

  .form-inputs
    = f.association :immonet_mail
    = f.input :object_id
    = f.input :link
    = f.input :status

  .form-actions
    = f.button :submit

app/views/immonet_links/edit.html.haml
%h1 Editing immonet_link

= render 'form'

= link_to 'Show', @immonet_link
\|
= link_to 'Back', immonet_links_path

app/views/immonet_links/index.html.haml
%h1 Listing immonet_links

%table
  %tr
    %th Immonet mail
    %th Object
    %th Link
    %th Status
    %th
    %th
    %th

  - @immonet_links.each do |immonet_link|
    %tr
      %td= immonet_link.immonet_mail
      %td= immonet_link.object_id
      %td= immonet_link.link
      %td= immonet_link.status
      %td= link_to 'Show', immonet_link
      %td= link_to 'Edit', edit_immonet_link_path(immonet_link)
      %td= link_to 'Destroy', immonet_link, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Immonet link', new_immonet_link_path

app/views/immonet_links/new.html.haml
%h1 New immonet_link

= render 'form'

= link_to 'Back', immonet_links_path

app/views/immonet_links/show.html.haml
%p#notice= notice

%p
  %b Immonet mail:
  = @immonet_link.immonet_mail
%p
  %b Object:
  = @immonet_link.object_id
%p
  %b Link:
  = @immonet_link.link
%p
  %b Status:
  = @immonet_link.status

= link_to 'Edit', edit_immonet_link_path(@immonet_link)
\|
= link_to 'Back', immonet_links_path